<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-201701161129" name="default" tests="12" failures="1" timestamp="6 Dec 2018 03:26:49 GMT" time="179.468" errors="0">
  <testcase name="login" time="19.746" classname="com.miao.testcases.MemberShipTest"/>
  <testcase name="enteringBlood" time="3.448" classname="com.miao.testcases.MemberShipTest"/>
  <testcase name="login" time="14.351" classname="com.miao.testcases.MemberRiskTest"/>
  <testcase name="enterRisk" time="10.502" classname="com.miao.testcases.MemberRiskTest"/>
  <testcase name="login" time="14.122" classname="com.miao.testcases.MemberFitnessTest"/>
  <testcase name="fitnessEnter" time="22.871" classname="com.miao.testcases.MemberFitnessTest"/>
  <testcase name="login" time="17.285" classname="com.miao.testcases.MemberFramminghamTest"/>
  <testcase name="framminghamEnter" time="5.05" classname="com.miao.testcases.MemberFramminghamTest"/>
  <testcase name="login" time="17.159" classname="com.miao.testcases.MemberSleepAssessmentTest"/>
  <testcase name="sleepAssessment" time="5.693" classname="com.miao.testcases.MemberSleepAssessmentTest">
    <failure type="java.lang.AssertionError" message="expected [https://cmstest.morewellness.cn/#/member/v2/evaluate/sleep/] but found [https://cmstest.morewellness.cn/#/member/v2/evaluate/sleep/create/]">
      <![CDATA[java.lang.AssertionError: expected [https://cmstest.morewellness.cn/#/member/v2/evaluate/sleep/] but found [https://cmstest.morewellness.cn/#/member/v2/evaluate/sleep/create/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.miao.testcases.MemberSleepAssessmentTest.sleepAssessment(MemberSleepAssessmentTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- sleepAssessment -->
  <testcase name="login" time="17.318" classname="com.miao.testcases.MemberNutrilonalAssessmentTest"/>
  <testcase name="nutrilonEnter" time="4.413" classname="com.miao.testcases.MemberNutrilonalAssessmentTest"/>
</testsuite> <!-- default -->
